#!/bin/bash
zmienna=`tmux display-message -p '#S'`
tmux new-window -t $zmienna
tmux split-window -h -p 30 -t $zmienna
tmux split-window -v -p 25 -t $zmienna
tmux clock-mode -t $zmienna
tmux select-pane -t 1
