#!/bin/bash
zmienna=`tmux display-message -p '#S'`
tmux new-window -t $zmienna
tmux split-window -h -p 22 -t $zmienna
tmux split-window -v -p 15 -t $zmienna
tmux clock-mode -t $zmienna
tmux select-pane -t 1
