#!/bin/bash
tmux new-session -s $1 -n editor -d
tmux send-keys -t $1 'cd ~/' C-m
tmux send-keys -t $1 'vim' C-m
tmux split-window -h -p 22 -t $1
tmux split-window -v -p 15 -t $1
##tmux select-layout -t $1 main-horizontal
tmux clock-mode -t $1
tmux new-window -n dev -t $1
tmux split-window -h -p 22 -t $1:2
tmux split-window -v -p 15 -t $1:2
tmux clock-mode -t $1:2
tmux select-window -t editor
tmux select-pane -t 1
